// OntaDev_Libs Plugin
// Авторские права (c) 2026 OntaDev
// Лицензия: MIT

package com.ontadev.libs.orm.database;

import java.util.regex.Pattern;

@SuppressWarnings("unused")
public enum Dialect {
    MYSQL,
    POSTGRESQL,
    H2,
    H2_POSTGRES;

    private static final Pattern H2_POSTGRES_MODE =
            Pattern.compile("(?i)MODE\\s*=\\s*PostgreSQL");

    public static Dialect fromJdbcUrl(String jdbcUrl) {
        if (jdbcUrl.startsWith("jdbc:mysql") || jdbcUrl.startsWith("jdbc:mariadb")) {
            return MYSQL;
        }
        if (jdbcUrl.startsWith("jdbc:postgresql")) {
            return POSTGRESQL;
        }
        if (jdbcUrl.startsWith("jdbc:h2")) {
            return H2_POSTGRES_MODE.matcher(jdbcUrl).find() ? H2_POSTGRES : H2;
        }
        throw new IllegalArgumentException("Неизвестный диалект для JDBC URL: " + jdbcUrl);
    }

    public String autoIncrementPrimaryKey() {
        switch (this) {
            case MYSQL:
                return "BIGINT PRIMARY KEY AUTO_INCREMENT";
            case POSTGRESQL:
                return "BIGSERIAL PRIMARY KEY";
            case H2:
            case H2_POSTGRES:
                return "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public String autoIncrement(){
        switch (this){
            case MYSQL:
            case H2:
                return "AUTO_INCREMENT";
            case H2_POSTGRES:
            case POSTGRESQL:
                return  "GENERATED BY DEFAULT AS IDENTITY";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public boolean supportMultiAutoIncrement(){
        switch (this){
            case H2_POSTGRES:
            case POSTGRESQL:
                return true;
            default:
                return false;
        }
    }

    public String varchar(int length) {
        switch (this) {
            case POSTGRESQL:
            case MYSQL:
            case H2:
            case H2_POSTGRES:
                return "VARCHAR(" + length + ")";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public String text() {
        return "TEXT";
    }

    public String integer() {
        switch (this) {
            case POSTGRESQL:
            case MYSQL:
            case H2:
            case H2_POSTGRES:
                return "INT";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public String bigint() {
        switch (this) {
            case MYSQL:
            case POSTGRESQL:
            case H2:
            case H2_POSTGRES:
                return "BIGINT";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public String bool() {
        switch (this) {
            case MYSQL:
                return "TINYINT(1)";
            case POSTGRESQL:
            case H2:
            case H2_POSTGRES:
                return "BOOLEAN";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public String doubleType() {
        switch (this) {
            case MYSQL:
                return "DOUBLE";
            case POSTGRESQL:
            case H2:
            case H2_POSTGRES:
                return "DOUBLE PRECISION";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    public String decimal(int precision, int scale) {
        switch (this) {
            case MYSQL:
            case POSTGRESQL:
            case H2:
            case H2_POSTGRES:
                return "DECIMAL(" + precision + "," + scale + ")";
            default:
                throw new IllegalStateException("Unexpected database type: " + this);
        }
    }

    /** REPLACE INTO не поддерживается в Postgres. */
    public boolean supportsReplaceInto() {
        return this == MYSQL;
    }

    /**
     * Для PostgreSQL и H2 в режиме MODE=PostgreSQL.
     */
    public boolean supportsOnConflict() {
        return this == POSTGRESQL || this == H2_POSTGRES;
    }

    public boolean usesMergeInto() {
        return this == H2;
    }
}