// OntaDev_Libs Plugin
// Авторские права (c) 2026 OntaDev
// Лицензия: MIT

package com.ontadev.libs.orm;

import com.ontadev.libs.config.SettingsConfig;
import com.ontadev.libs.ioc.IoCContainer;
import com.ontadev.libs.orm.adapter.EntityRowMapperFactory;
import com.ontadev.libs.orm.annotation.Query;
import com.ontadev.libs.orm.annotation.entity.Column;
import com.ontadev.libs.orm.annotation.entity.Entity;
import com.ontadev.libs.orm.annotation.entity.GeneratedValue;
import com.ontadev.libs.orm.annotation.entity.Id;
import com.ontadev.libs.orm.annotation.entity.Table;
import com.ontadev.libs.orm.database.DatabaseManager;
import com.ontadev.libs.orm.dto.DatabaseSettings;
import com.ontadev.libs.orm.entity.SchemaGenerator;
import com.ontadev.libs.orm.mapper.EntityMapper;
import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.util.Optional;
import java.util.UUID;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Тот же путь save/find, что и в {@link OrmTest}, но на живом Postgres —
 * запущенном через embedded-postgres (нативный бинарник процессом, без Docker),
 * чтобы поймать диалект-специфичные баги DDL (у Postgres, например, BIGSERIAL
 * вместо GENERATED BY DEFAULT AS IDENTITY), которых H2/SQLite не покрывают.
 */
public class OrmPostgresTest {

    @Entity
    @Table("players")
    static class Player {

        @Id
        @GeneratedValue
        private Long id;

        @Column
        private String nickname;
    }

    interface PlayerRepository extends OrmRepository<Player, Long> {

        @Query("SELECT * FROM players WHERE nickname = ?")
        Optional<Player> findByNickname(String nickname);
    }

    @Test
    void shouldGenerateSchemaAndSaveOnPostgres() throws IOException {
        try (EmbeddedPostgres postgres = startOrSkip()) {
            IoCContainer container = mock(IoCContainer.class);

            DatabaseManager databaseManager = new DatabaseManager(new SettingsConfig(new DatabaseSettings(
                    postgres.getJdbcUrl("postgres", "postgres"),
                    "postgres",
                    "postgres",
                    2,
                    1,
                    30000L,
                    600000L,
                    1800000L
            )));

            EntityMapper entityMapper = new EntityMapper(databaseManager.getDialect());
            SchemaGenerator generator = new SchemaGenerator(databaseManager, entityMapper);

            EntityRowMapperFactory entityRowMapperFactory = new EntityRowMapperFactory(entityMapper);
            databaseManager.getJdbi().registerRowMapper(entityRowMapperFactory);

            when(container.get(DatabaseManager.class)).thenReturn(databaseManager);
            when(container.get(SchemaGenerator.class)).thenReturn(generator);
            when(container.get(EntityMapper.class)).thenReturn(entityMapper);

            PlayerRepository result = new OrmRepositoryHandler().createRealization(container, PlayerRepository.class);

            Player player = new Player();
            player.nickname = "steve-" + UUID.randomUUID();

            Player saved = result.save(player);
            Assertions.assertNotNull(saved.id);

            Optional<Player> found = result.findByNickname(player.nickname);
            Assertions.assertTrue(found.isPresent());
            Assertions.assertEquals(saved.id, found.get().id);

            databaseManager.shutdown();
        }
    }

    /** На платформах без готового бинарника (например, экзотичная архитектура) тест мягко скипается. */
    private static EmbeddedPostgres startOrSkip() {
        try {
            return EmbeddedPostgres.start();
        } catch (IOException | RuntimeException exception) {
            Assumptions.abort("Embedded Postgres недоступен на этой платформе: " + exception.getMessage());
            throw new AssertionError("unreachable");
        }
    }
}
